name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Copy CNAME
        run: cp public/CNAME dist/

      - name: Configure headers
        run: |
          cat > ./dist/_headers << EOL
          /*
            Content-Type: text/html; charset=utf-8
            Permissions-Policy: interest-cohort=(), private-state-token-redemption=(), private-state-token-issuance=()
          /*.js
            Content-Type: application/javascript; charset=utf-8
          /*.mjs
            Content-Type: application/javascript; charset=utf-8
          /*.css
            Content-Type: text/css; charset=utf-8
          /*.png
            Content-Type: image/png
          /*.jpg
            Content-Type: image/jpeg
          /*.svg
            Content-Type: image/svg+xml
          EOL

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          static_site_generator: vite

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 